### ISSUE TITLE
Where are the files? 

### ISSUE THREAD

**Issue by jaconfurz** [gotkrypto76/TeensyTAS#1]
Release page is empty and there is only the license and read me file.

**Comment by gotkrypto76** [comment]
Hey, sorry about that. This project is nowhere near ready for a release just yet, so I’ve been holding back on publicly releasing my source code. It’s currently just a side-project, and I’ve been pretty busy with schooling and job stuff, so I haven’t been able to dedicate a lot of my time to it.

I have eventual plans on releasing this. But I don’t know entirely when that would be. I may scrap the Arduino implementation and see if I can’t make a sysmodule or something for one of the currently out there CFWs. 

I hope this answers your question,
Maxwell

**Comment by jaconfurz** [comment]
Okay, thank you for the explanation! I'll keep an eye on this, see what comes up.
